### ISSUE TITLE
Automate version updates across dependent Terraform modules

### ISSUE THREAD

**Issue by bobbyiliev** [MaterializeInc/terraform-helm-materialize#15]
When we release a new version of terraform-helm-materialize, we need to update the module reference in:
- `terraform-aws-materialize`
- `terraform-azurerm-materialize`
- `terraform-google-materialize`

Let's automate this with a GitHub Action that creates PRs in each repository when a new tag is pushed.

1. We would need a GH access token?
2. Workflow file

**Comment by bobbyiliev** [comment]
Maybe a GH action that could work:

```yaml
name: Update Module Version in Dependent Repos

on:
 push:
   tags:
     - 'v*'

jobs:
 update-version:
   runs-on: ubuntu-latest
   strategy:
     matrix:
       repo: ['terraform-aws-materialize', 'terraform-azurerm-materialize', 'terraform-google-materialize']
   
   steps:
     - name: Get the version
       id: get_version
       run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

     - name: Checkout dependent repository
       uses: actions/checkout@v4
       with:
         repository: MaterializeInc/${{ matrix.repo }}
         token: ${{ secrets.GH_PAT }}

     - name: Update version reference
       run: |
         sed -i 's|github.com/MaterializeInc/terraform-helm-materialize?ref=v[0-9.]*|github.com/MaterializeInc/terraform-helm-materialize?ref=${{ steps.get_version.outputs.VERSION }}|' main.tf

     - name: Create Pull Request
       uses: peter-evans/create-pull-request@v6
       with:
         token: ${{ secrets.GH_PAT }}
         branch: update-helm-module-${{ steps.get_version.outputs.VERSION }}
         title: "chore: Update terraform-helm-materialize to ${{ steps.get_version.outputs.VERSION }}"
         body: |
           Updates terraform-helm-materialize module to version ${{ steps.get_version.outputs.VERSION }}.
           
           This PR was automatically generated.
         commit-message: "chore: bump terraform-helm-materialize to ${{ steps.get_version.outputs.VERSION }}"
         committer: GitHub <noreply@github.com>
         author: GitHub <noreply@github.com>
         labels: dependencies
         base: main
         delete-branch: true
         signoff: true
```
